version: "3.9"

services:

  postgres:
    image: pgvector/pgvector:pg16
    container_name: products_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: products_api
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg://app:app@postgres:5432/products_db
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads


  adminer:
    image: adminer
    container_name: products_adminer
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data: