version: "3.9"

services:

  postgres:
    image: pgvector/pgvector:pg16
    container_name: products_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  image-search-api:
    build:
      context: ./image-search-api
      dockerfile: Dockerfile
    container_name: image_search_api
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - ./image-search-api/.env
    environment:
      DATABASE_URL: postgresql+psycopg://app:app@postgres:5432/products_db
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./image-search-api/uploads:/app/uploads

  product-description-api:
    build:
      context: ./product-description-api
      dockerfile: Dockerfile
    container_name: product_description_api
    restart: unless-stopped
    env_file:
      - ./product-description-api/.env
    ports:
      - "8081:8080"
  streamlit:
    build:
      context: ./streamlit-app
      dockerfile: Dockerfile
    container_name: product_streamlit
    restart: unless-stopped
    ports:
      - "8501:8080"
    environment:
      IMAGE_SEARCH_API_URL: http://image-search-api:8000
      PRODUCT_DESCRIPTION_API_URL: http://product-description-api:8080/generate-product-description
    depends_on:
      - image-search-api
      - product-description-api

      
  adminer:
    image: adminer
    container_name: products_adminer
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data: